### ISSUE TITLE
GreyNoise API configuration issue

### ISSUE THREAD

**Issue by exente** [ecstatic-nobel/osweep#2]
Hi,

I've a GreyNoise API key and I want to test it on the platform, but as soon as I set it up on the config.py file, the APP does not work, is not able to download any feed. There is required any format, quotations or something like that?

PS: I would like to add also the twitter API ones, but firts I prefer to identify how to configure it

Thanks in advance

**Comment by ecstatic-nobel** [comment]
Thanks for reporting this. Are you seeing any errors in Splunk? Also, please ensure that all value, with the exception of 'None', is surrounded by quotes. Commit `d7ec95c39d667bd6bfc7579466e5297342fa3d84` was just pushed to show this in the comments of the `config.py`.

Let me know if this helps.

**Comment by exente** [comment]
That works! I'm sorry to come with this newbie question :)
