### ISSUE TITLE
 Search is waiting for input...

### ISSUE THREAD

**Issue by sagar3506** [ecstatic-nobel/osweep#4]
hi @ecstatic-nobel i setup your project its really cool but got this error  Search is waiting for input...
what should i need to do ?

![image](https://user-images.githubusercontent.com/9415704/59354530-efad9800-8d42-11e9-8584-a68775105ae3.png)

**Comment by sagar3506** [comment]
@ecstatic-nobel sorry for silly question i didn`t check manual properly now it working great

**Comment by keep-learning-go** [comment]
Hey @sagar3506 , mind sharing a solution please?
I'm very new to Splunk and I've gone thru installation docs for several times, still, can't find source of issue :/
I'm on Ubuntu 18.04 LTS with latest Splunk Enterprise 7.3.0

**Comment by TheFausap** [comment]
The panels are waiting for the input in the InputBox IOC.
